services:
  bot:
    build:
      dockerfile: ./Dockerfile
    container_name: weightliftingbot
    restart: unless-stopped
    ports:
      - "10081:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      DISCORD_TOKEN: "${DISCORD_TOKEN}"

  redis:
    image: redis:8.2.1
    container_name: weightliftingredis
    restart: unless-stopped
    ports:
      - "9379:6379"
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
